[phases.setup]
nixPkgs = [
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "dbus",
  "libdrm",
  "libxkbcommon",
  "libXcomposite",
  "libXdamage",
  "libXfixes",
  "libXrandr",
  "mesa",
  "alsa-lib"
]
