/**
 * Evidence-Based Recommendation Generator
 *
 * Takes collected evidence (business type, social analysis, brand positioning,
 * competitor data, findings) and uses GPT to generate specific,
 * evidence-grounded recommendations. Falls back to template-based
 * recommendations when GPT is unavailable.
 *
 * Principle: Every recommendation must cite specific evidence from the audit.
 * No generic advice like "improve your SEO" without a specific page or metric.
 */

import type { BusinessClassification } from "./business-type-classifier";

// ─────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────

export interface RecommendationEvidenceSource {
  /** Category of evidence: business-type | social | brand | competitor | seo | technical */
  category: string;
  /** Specific evidence string */
  detail: string;
  /** Confidence in this evidence 0-100 */
  confidence?: number;
}

export interface EvidenceBackedRecommendation {
  id: string;
  title: string;
  description: string;
  priority: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  effort: "QUICK_WIN" | "MODERATE" | "SIGNIFICANT" | "MAJOR_PROJECT";
  category: "marketing" | "social" | "content" | "brand" | "seo" | "technical";
  /** The evidence that backs this recommendation */
  evidence: RecommendationEvidenceSource[];
  /** Expected impact when implemented */
  expectedImpact: string;
  /** Implementation steps */
  steps: string[];
  /** Whether this was generated by AI or template-based */
  generatedBy: "ai" | "template";
}

export interface RecommendationContext {
  domain: string;
  businessClassification?: BusinessClassification;
  brandPositioning?: {
    industryCategory?: string;
    businessModel?: string;
    valueProposition?: string;
    contentGaps?: string[];
    confidence?: number;
  };
  socialAnalysis?: {
    socialStrength?: number;
    platformCount?: number;
    confidence?: string;
    brandAlignment?: {
      status?: string;
      score?: number;
      evidenceLevel?: number;
    };
    recommendations?: string[];
    weaknesses?: string[];
    dataGaps?: string[];
  };
  competitors?: {
    count?: number;
    primaryGaps?: string[];
    quickWins?: string[];
    dataQuality?: string;
  };
  seoAndTechnical?: {
    criticalIssues?: number;
    warnings?: number;
    topIssues?: Array<{ title: string; severity: string }>;
  };
  pageCount?: number;
  hasBlog?: boolean;
  hasCaseStudies?: boolean;
  hasPricing?: boolean;
}

// ─────────────────────────────────────────
// MAIN FUNCTIONS
// ─────────────────────────────────────────

/**
 * Build the evidence context from all available audit data.
 */
export function buildRecommendationContext(params: {
  domain: string;
  businessClassification?: BusinessClassification;
  brandPositioning?: Record<string, unknown>;
  socialAnalysis?: Record<string, unknown>;
  competitorResult?: Record<string, unknown>;
  findings?: Array<Record<string, unknown>>;
  crawledPages?: Array<Record<string, unknown>>;
  pageCount?: number;
}): RecommendationContext {
  const ctx: RecommendationContext = { domain: params.domain };

  if (params.businessClassification) {
    ctx.businessClassification = params.businessClassification;
  }

  if (params.brandPositioning) {
    const bp = params.brandPositioning;
    ctx.brandPositioning = {
      industryCategory: bp.industryCategory as string | undefined,
      businessModel: bp.businessModel as string | undefined,
      valueProposition: bp.valueProposition as string | undefined,
      contentGaps: bp.contentGaps as string[] | undefined,
      confidence: bp.confidence as number | undefined,
    };
  }

  if (params.socialAnalysis) {
    const sa = params.socialAnalysis;
    ctx.socialAnalysis = {
      socialStrength: sa.social_strength as number | undefined,
      platformCount: (sa.platform_health as Array<unknown> | undefined)?.length,
      confidence: sa.confidence as string | undefined,
      brandAlignment: sa.brand_alignment
        ? {
            status: (sa.brand_alignment as Record<string, unknown>).status as string | undefined,
            score: (sa.brand_alignment as Record<string, unknown>).score as number | undefined,
            evidenceLevel: (sa.brand_alignment as Record<string, unknown>).evidenceLevel as number | undefined,
          }
        : undefined,
      recommendations: sa.recommendations as string[] | undefined,
      weaknesses: sa.weaknesses as string[] | undefined,
      dataGaps: sa.insufficient_data_reasons as string[] | undefined,
    };
  }

  if (params.competitorResult) {
    const cr = params.competitorResult;
    ctx.competitors = {
      count: (cr.competitors as Array<unknown> | undefined)?.length,
      primaryGaps: (cr.summary as Record<string, unknown> | undefined)?.primaryGaps as string[] | undefined,
      quickWins: (cr.summary as Record<string, unknown> | undefined)?.quickWins as string[] | undefined,
      dataQuality: cr.dataQuality as string | undefined,
    };
  }

  if (params.findings) {
    const criticals = params.findings.filter(
      f => (f.severity as string) === "CRITICAL" || (f.severity as string) === "ERROR"
    );
    const warnings = params.findings.filter(w => (w.severity as string) === "WARNING");
    ctx.seoAndTechnical = {
      criticalIssues: criticals.length,
      warnings: warnings.length,
      topIssues: params.findings.slice(0, 5).map(f => ({
        title: (f.title || f.type || "") as string,
        severity: (f.severity as string),
      })),
    };
  }

  ctx.pageCount = params.pageCount || params.crawledPages?.length || 0;

  // Detect content presence from crawled pages
  if (params.crawledPages && params.brandPositioning?.contentThemes) {
    const urls = params.crawledPages.map(p => ((p.url || "") as string).toLowerCase());
    const themes = params.brandPositioning.contentThemes as Array<Record<string, unknown>>;
    const topics = themes.map(t => (t.topic || "") as string);
    ctx.hasBlog = urls.some(u => /\/blog\//.test(u)) || topics.some(t => /blog/i.test(t));
    ctx.hasCaseStudies = urls.some(u => /case.stud/i.test(u)) || topics.some(t => /case.stud/i.test(t));
    ctx.hasPricing = urls.some(u => /pricing|plans?/.test(u)) || topics.some(t => /pricing/i.test(t));
  } else if (params.crawledPages) {
    const urls = params.crawledPages.map(p => ((p.url || "") as string).toLowerCase());
    ctx.hasBlog = urls.some(u => /\/blog\//.test(u));
    ctx.hasCaseStudies = urls.some(u => /case.stud/i.test(u));
    ctx.hasPricing = urls.some(u => /pricing|plans?/.test(u));
  }

  return ctx;
}

/**
 * Generate evidence-backed recommendations using GPT when available.
 * Falls back to template-based recommendations otherwise.
 */
export async function generateEvidenceBasedRecommendations(
  context: RecommendationContext
): Promise<EvidenceBackedRecommendation[]> {
  const apiKey = process.env.OPENAI_API_KEY || process.env.OPEN_API_KEY || "";

  if (apiKey && apiKey.startsWith("sk-")) {
    try {
      return await generateWithAI(context, apiKey);
    } catch {
      // Fall through to template-based
    }
  }

  return generateWithTemplates(context);
}

// ─────────────────────────────────────────
// AI-BASED GENERATION
// ─────────────────────────────────────────

async function generateWithAI(
  context: RecommendationContext,
  apiKey: string
): Promise<EvidenceBackedRecommendation[]> {
  const { OpenAI } = await import("openai");
  const client = new OpenAI({ apiKey });

  // Truncate context to avoid token limits on gpt-4o-mini
  const contextStr = JSON.stringify(context, null, 2);
  const truncated = contextStr.length > 6000 ? contextStr.slice(0, 6000) + "\n... [truncated]" : contextStr;

  const result = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [{
      role: "user",
      content: `You are a Chief Marketing Officer creating a strategic action plan for ${context.domain}.

Below is audit evidence. Generate exactly 5-7 specific, actionable recommendations.

RULES:
- Every recommendation MUST cite specific evidence from the data provided.
- No generic advice. If a recommendation could apply to any company, rewrite it.
- Prioritize by ROI: quick wins first, strategic initiatives second.
- Consider the business type and industry.
- Include specific metrics, pages, or comparisons when evidence supports it.

EVIDENCE CONTEXT:
${truncated}

Return a JSON object with key "recommendations" containing an array of:
{
  "title": "Short specific title",
  "description": "What to do and why (2-3 sentences, citing evidence)",
  "priority": "CRITICAL|HIGH|MEDIUM|LOW",
  "effort": "QUICK_WIN|MODERATE|SIGNIFICANT|MAJOR_PROJECT",
  "category": "marketing|social|content|brand|seo|technical",
  "expectedImpact": "What will improve",
  "steps": ["Step 1", "Step 2", "Step 3"]
}

Return ONLY valid JSON, no markdown.`,
    }],
    temperature: 0.4,
    max_tokens: 1500,
    response_format: { type: "json_object" },
  });

  const text = result.choices[0]?.message?.content || "{}";
  const parsed = JSON.parse(text.replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim());
  const items = Array.isArray(parsed) ? parsed : (parsed.recommendations || []);

  if (!Array.isArray(items) || items.length === 0) {
    return generateWithTemplates(context);
  }

  return items.slice(0, 7).map((item: Record<string, unknown>, i: number) => ({
    id: `ai_rec_${i + 1}`,
    title: String(item.title || `Recommendation ${i + 1}`),
    description: String(item.description || ""),
    priority: validatePriority(String(item.priority || "HIGH")),
    effort: validateEffort(String(item.effort || "MODERATE")),
    category: validateCategory(String(item.category || "marketing")),
    evidence: [{ category: (item.category as string) || "analysis", detail: context.domain }],
    expectedImpact: String(item.expectedImpact || ""),
    steps: Array.isArray(item.steps) ? item.steps.map(String) : [],
    generatedBy: "ai" as const,
  }));
}

// ─────────────────────────────────────────
// TEMPLATE-BASED FALLBACK
// ─────────────────────────────────────────

function generateWithTemplates(
  context: RecommendationContext
): EvidenceBackedRecommendation[] {
  const recommendations: EvidenceBackedRecommendation[] = [];
  const bc = context.businessClassification;
  const bp = context.brandPositioning;
  const sa = context.socialAnalysis;
  const comp = context.competitors;
  const tech = context.seoAndTechnical;

  let idCounter = 0;
  const nextId = () => `template_rec_${++idCounter}`;

  // 1. Content gap recommendations (from business type)
  if (bp?.contentGaps && bp.contentGaps.length > 0) {
    for (const gap of bp.contentGaps.slice(0, 3)) {
      const isCaseStudyGap = /case.stud/i.test(gap);
      recommendations.push({
        id: nextId(),
        title: `Create ${isCaseStudyGap ? "case studies" : "missing content assets"}`,
        description: `${gap} — This is a critical content gap for a ${bc?.businessType || "this"} business.`,
        priority: "HIGH",
        effort: isCaseStudyGap ? "SIGNIFICANT" : "MODERATE",
        category: "content",
        evidence: [
          { category: "business-type", detail: `Business type: ${bc?.businessType || "unknown"}` },
          { category: "content-gap", detail: gap },
        ],
        expectedImpact: "Improved SEO visibility and conversion rate through better content coverage",
        steps: isCaseStudyGap
          ? ["Identify 2-3 customers willing to participate", "Conduct customer interviews focusing on measurable outcomes", "Write case studies with format: Challenge / Solution / Results", "Publish and promote on social channels"]
          : ["Audit existing content for the identified gap", "Create a content brief targeting the missing topic", "Write and publish the content", "Promote through relevant channels"],
        generatedBy: "template" as const,
      });
    }
  }

  // 2. Social recommendations (from social analysis)
  if (sa?.socialStrength !== undefined && sa.socialStrength < 50 && sa.confidence !== "low") {
    recommendations.push({
      id: nextId(),
      title: "Strengthen social content strategy",
      description: `Social strength is ${sa.socialStrength}/100 across ${sa.platformCount || 0} platforms. Focus on content pillars that align with brand positioning to improve engagement and consistency.`,
      priority: "MEDIUM",
      effort: "MODERATE",
      category: "social",
      evidence: [
        { category: "social", detail: `Social strength: ${sa.socialStrength}/100` },
        { category: "social", detail: `Platforms: ${sa.platformCount || 0}` },
      ],
      expectedImpact: "Improved social engagement and brand consistency",
      steps: [
        "Audit current social content mix against brand messaging pillars",
        "Define 3-4 content pillars with specific KPIs per platform",
        "Create a 30-day content calendar aligning social content to positioning",
        "Monitor engagement rates weekly and adjust",
      ],
      generatedBy: "template" as const,
    });
  }

  // Brand alignment recommendation
  if (sa?.brandAlignment && sa.brandAlignment.status === "partial-mismatch") {
    recommendations.push({
      id: nextId(),
      title: "Align social content with brand positioning",
      description: `Brand alignment score: ${sa.brandAlignment.score}/100 (Level ${sa.brandAlignment.evidenceLevel || 1}). Website positioning and social content themes have partial misalignment.`,
      priority: "HIGH",
      effort: "MODERATE",
      category: "brand",
      evidence: [
        { category: "brand-consistency", detail: `Alignment: ${sa.brandAlignment.status}` },
        { category: "brand-consistency", detail: `Score: ${sa.brandAlignment.score}` },
      ],
      expectedImpact: "Consistent brand messaging across channels improves trust and recall",
      steps: [
        "Document current website positioning statements",
        "Audit last 30 social posts for message alignment",
        "Create messaging guidelines for social content",
        "Retrain social team on brand voice and messaging pillars",
      ],
      generatedBy: "template" as const,
    });
  }

  // 3. Competitor-based recommendations
  if (comp?.count && comp.count > 0 && comp.primaryGaps && comp.primaryGaps.length > 0) {
    recommendations.push({
      id: nextId(),
      title: "Address competitive positioning gaps",
      description: `${comp.count} competitors identified. Key gaps: ${comp.primaryGaps.slice(0, 2).join("; ")}. These represent differentiation opportunities.`,
      priority: "HIGH",
      effort: "SIGNIFICANT",
      category: "marketing",
      evidence: [
        { category: "competitor", detail: `${comp.count} competitors found` },
        ...comp.primaryGaps.slice(0, 2).map(g => ({ category: "competitor-gap" as const, detail: g })),
      ],
      expectedImpact: "Improved competitive position and market differentiation",
      steps: [
        "Deep-dive into top 2 competitor websites and social channels",
        "Identify specific messaging, content, or feature gaps",
        "Prioritize 2-3 gaps to address in the next quarter",
        "Create execution plan with ownership and timeline",
      ],
      generatedBy: "template" as const,
    });
  }

  // 4. Technical/SEO recommendations
  if (tech?.criticalIssues && tech.criticalIssues > 0) {
    const topIssue = tech.topIssues?.[0];
    recommendations.push({
      id: nextId(),
      title: topIssue ? `Fix: ${topIssue.title}` : "Address critical technical issues",
      description: `${tech.criticalIssues} critical issue(s) and ${tech.warnings || 0} warnings detected. ${topIssue ? `Top priority: ${topIssue.title}.` : ""}`,
      priority: "CRITICAL",
      effort: tech.criticalIssues <= 3 ? "MODERATE" : "SIGNIFICANT",
      category: "technical",
      evidence: [
        { category: "technical", detail: `${tech.criticalIssues} critical issues` },
        ...(tech.topIssues?.slice(0, 2).map(t => ({ category: "technical" as const, detail: `${t.severity}: ${t.title}` })) || []),
      ],
      expectedImpact: "Improved search crawlability, indexation, and page experience",
      steps: [
        "Review and prioritize all critical findings",
        "Assign ownership per finding type (development, content, SEO)",
        "Fix in order of business impact (critical pages first)",
        "Re-run audit to verify fixes",
      ],
      generatedBy: "template" as const,
    });
  }

  // 5. Industry-specific recommendations from business type
  if (bc && bc.businessType !== "unknown") {
    if (context.hasBlog === false && bc.businessType === "b2b-saas") {
      recommendations.push({
        id: nextId(),
        title: "Launch a content blog for organic acquisition",
        description: `As a ${bc.businessType} company, an active blog is a critical SEO channel. No blog content was detected. Competitors are likely capturing organic traffic through educational content.`,
        priority: "HIGH",
        effort: "SIGNIFICANT",
        category: "content",
        evidence: [
          { category: "business-type", detail: `Type: ${bc.businessType}` },
          { category: "content-gap", detail: "No blog content detected" },
        ],
        expectedImpact: "Long-term organic traffic growth and lead generation",
        steps: [
          "Define 10-15 core content topics based on customer pain points",
          "Create a publishing calendar (2-4 posts/month to start)",
          "Write foundational pillar pages for top-priority keywords",
          "Implement proper SEO structure: titles, meta, schema, internal links",
        ],
        generatedBy: "template" as const,
      });
    }

    if (context.hasCaseStudies === false && (bc.businessType === "b2b-saas" || bc.businessType === "b2b-services")) {
      recommendations.push({
        id: nextId(),
        title: "Publish customer case studies",
        description: `No case studies detected. For ${bc.businessType} businesses, case studies are critical conversion tools that provide social proof and demonstrate ROI.`,
        priority: "HIGH",
        effort: "MODERATE",
        category: "content",
        evidence: [
          { category: "business-type", detail: `Type: ${bc.businessType}` },
          { category: "content-gap", detail: "No case studies found" },
        ],
        expectedImpact: "Improved conversion rates through social proof",
        steps: [
          "Select 2-3 customers with measurable results",
          "Interview customers on challenges, solution, outcomes",
          "Write case studies with quantifiable results",
          "Feature on homepage, service pages, and sales materials",
        ],
        generatedBy: "template" as const,
      });
    }

    if (context.hasPricing === false && (bc.businessType === "b2b-saas" || bc.businessType === "b2b-services")) {
      recommendations.push({
        id: nextId(),
        title: "Add pricing page",
        description: `No pricing page detected. For ${bc.businessType} businesses, transparent pricing builds trust and helps qualify leads.`,
        priority: "MEDIUM",
        effort: "MODERATE",
        category: "marketing",
        evidence: [
          { category: "business-type", detail: `Type: ${bc.businessType}` },
          { category: "content-gap", detail: "No pricing page found" },
        ],
        expectedImpact: "Better lead qualification and reduced sales friction",
        steps: [
          "Define pricing tiers based on features and value metrics",
          "Design pricing page with clear comparison table",
          "Add FAQ section addressing common pricing questions",
          "Include clear CTA for each tier",
        ],
        generatedBy: "template" as const,
      });
    }
  }

  // 6. General growth recommendations
  if (context.pageCount !== undefined && context.pageCount < 10) {
    recommendations.push({
      id: nextId(),
      title: "Expand website content and page depth",
      description: `Only ${context.pageCount} pages were discovered. Limited site depth restricts SEO visibility and opportunities to rank for relevant keywords.`,
      priority: "MEDIUM",
      effort: "SIGNIFICANT",
      category: "content",
      evidence: [{ category: "seo", detail: `Only ${context.pageCount} pages crawled` }],
      expectedImpact: "Increased organic search visibility through more landing pages",
      steps: [
        "Audit current content for expansion opportunities",
        "Identify keyword gaps with high search volume",
        "Create 10-15 new pages targeting those keywords",
        "Interlink new content with existing pages for SEO",
      ],
      generatedBy: "template" as const,
    });
  }

  // Ensure we return at least some recommendations
  if (recommendations.length === 0) {
    recommendations.push({
      id: nextId(),
      title: "Complete the initial marketing audit baseline",
      description: "Not enough evidence was collected to generate specific recommendations. Run a deeper crawl and connect social API keys to enable data-driven recommendations.",
      priority: "MEDIUM",
      effort: "MODERATE",
      category: "marketing",
      evidence: [{ category: "analysis", detail: "Insufficient evidence collected" }],
      expectedImpact: "Clearer marketing roadmap",
      steps: [
        "Run a deeper website crawl (more pages)",
        "Connect Instagram, LinkedIn, and Facebook API keys",
        "Set up competitor tracking for ongoing analysis",
      ],
      generatedBy: "template" as const,
    });
  }

  return recommendations.slice(0, 7);
}

// ─────────────────────────────────────────
// VALIDATORS
// ─────────────────────────────────────────

function validatePriority(value: string): "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" {
  const valid = ["CRITICAL", "HIGH", "MEDIUM", "LOW"];
  return valid.includes(value) ? (value as "CRITICAL") : "HIGH";
}

function validateEffort(value: string): "QUICK_WIN" | "MODERATE" | "SIGNIFICANT" | "MAJOR_PROJECT" {
  const valid = ["QUICK_WIN", "MODERATE", "SIGNIFICANT", "MAJOR_PROJECT"];
  return valid.includes(value) ? (value as "QUICK_WIN") : "MODERATE";
}

function validateCategory(value: string): "marketing" | "social" | "content" | "brand" | "seo" | "technical" {
  const valid = ["marketing", "social", "content", "brand", "seo", "technical"];
  return valid.includes(value) ? (value as "marketing") : "marketing";
}
